clc;clear;
% FIGURE
f = figure ("name","DLSU MIR MP1 - Image Retrieval by Emberda and Balaman",...
            "position", [100 100 1000 500]);


            
% PANEL
p1 = uipanel ("title", "Action",...
             "position", [.03 .05 .24 .9]); %left bottom width height

p2 = uipanel ("title", "Result",...
             "position", [.28 .05 .7 .9],...
             "backgroundcolor",[0.85 0.85 0.85]); %left bottom width height


             
database_label = uicontrol (...
  "parent", p2,...
  "style", "text",...
  "units","normalized",...
  "string", "Image Database Path: ",...
  "horizontalalignment", "left",...
  "backgroundcolor",[0.85 0.85 0.85],...
  "position", [.035, 0.66, 0.2, 0.05]);    

total_images_label = uicontrol (...
  "parent", p2,...
  "style", "text",...
  "units","normalized",...
  "string", "Total Images: ",...
  "horizontalalignment", "left",...
  "backgroundcolor",[0.85 0.85 0.85],...
  "position", [.24, 0.90, 0.2, 0.05]);  
 
total_images = uicontrol (...
  "parent", p2,...
  "style", "text",...
  "units","normalized",...
  "string", "0",...
  "horizontalalignment", "left",...
  "backgroundcolor",[0.85 0.85 0.85],...
  "position", [.365, 0.90, 0.2, 0.05]);     

precision_label = uicontrol (...
  "parent", p2,...
  "style", "text",...
  "units","normalized",...
  "string", "Precision: ",...
  "horizontalalignment", "left",...
  "backgroundcolor",[0.85 0.85 0.85],...
  "position", [.24, 0.83, 0.2, 0.05]);  

precision = uicontrol (...
  "parent", p2,...
  "style", "text",...
  "units","normalized",...
  "string", "0",...
  "horizontalalignment", "left",...
  "backgroundcolor",[0.85 0.85 0.85],...
  "position", [.365, 0.83, 0.2, 0.05]);     

recall_label = uicontrol (...
  "parent", p2,...
  "style", "text",...
  "units","normalized",...
  "string", "Recall: ",...
  "horizontalalignment", "left",...
  "backgroundcolor",[0.85 0.85 0.85],...
  "position", [.24, 0.79, 0.2, 0.05]);  

recall = uicontrol (...
  "parent", p2,...
  "style", "text",...
  "units","normalized",...
  "string", "0",...
  "horizontalalignment", "left",...
  "backgroundcolor",[0.85 0.85 0.85],...
  "position", [.365, 0.79, 0.2, 0.05]);      
 
fmeasure_label = uicontrol (...
  "parent", p2,...
  "style", "text",...
  "units","normalized",...
  "string", "Fmeasure: ",...
  "horizontalalignment", "left",...
  "backgroundcolor",[0.85 0.85 0.85],...
  "position", [.24, 0.75, 0.2, 0.05]);  

fmeasure = uicontrol (...
  "parent", p2,...
  "style", "text",...
  "units","normalized",...
  "string", "0",...
  "horizontalalignment", "left",...
  "backgroundcolor",[0.85 0.85 0.85],...
  "position", [.365, 0.75, 0.2, 0.05]);     
  
database_path = uicontrol (...
  "parent", p2,...
  "style", "text",...
  "units","normalized",...
  "string", "Select directory...",...
  "horizontalalignment", "left",...
  "backgroundcolor",[0.85 0.85 0.85],...
  "position", [.22, 0.66, 0.75, 0.05]); 

query_path = uicontrol (...
  "parent", p2,...
  "style", "text",...
  "units","normalized",...
  "string", "Select query...",...
  "horizontalalignment", "left",...
  "backgroundcolor",[0.85 0.85 0.85],...
  "position", [.22, 1.89, 0.2, 0.05]);    
  
ImgQuery = axes ( ...
  "parent",   p2,...
  "position", [.02, 0.75, 0.2, 0.2]);
  imgQ = imread("0.png");
  axes(ImgQuery);
  imshow(imgQ,[]);
             
% BUTTONS
b1_label = uicontrol (...
  "parent", p1,...
  "style", "text",...
  "string", "Step 1: Choose Directory",...
  "horizontalalignment", "left",...
  "position", [18 390 200 36]);             
b1 = uicontrol (...
  "parent", p1,...
  "string", "Load Image Database",...
  "callback", {@load_image_database,database_path,total_images},...
  "position",[18 360 200 36]);
  
b2_label = uicontrol (...
  "parent", p1,...
  "style", "text",...
  "string", "Step 2: Choose Image",...
  "horizontalalignment", "left",...
  "position", [18 320 200 36]);    


method_label = uicontrol (...
  "parent", p1,...
  "style", "text",...
  "string", "Step 3: Choose Method",...
  "horizontalalignment", "left",...
  "position",[18 250 220 36]);

method_choice = uicontrol (...
  "parent", p1,...
  "style", "popupmenu",...
  "string", {"Color Histogram (CH)",...
            "CH with Perceptual Similarity",...
            "HistRefine with Color Coherence",...
            "CH with Centering Refinement"},...
  "position", [18 220 200 34]);
                            
b3_label = uicontrol (...
  "parent", p1,...
  "style", "text",...
  "string", "Step 4: Retrieve Images",...
  "horizontalalignment", "left",...
  "position", [18 180 200 36]);                    
                
                         

 
%tic 
imgR_1_label = uicontrol (...
  "parent", p2,...
  "style", "text",...
  "units","normalized",...
  "string", "",...
  "horizontalalignment", "center",...
  "foregroundcolor",[1 1 1],...
  "backgroundcolor",[0.85 0.85 0.85],...
  "position", [.023, 0.46, 0.143, 0.04]);  %-2 +1
  
ImgResult_1 = axes ( ...
    "parent",   p2,...
    "position", [.02, 0.5, 0.15, 0.15]);
imgR_1 = imread("0.png");
axes(ImgResult_1);
imshow(imgR_1,[]);

imgR_2_label = uicontrol (...
  "parent", p2,...
  "style", "text",...
  "units","normalized",...
  "string", "",...
  "horizontalalignment", "center",...
  "foregroundcolor",[1 1 1],...
  "backgroundcolor",[0.85 0.85 0.85],...
  "position", [.193, 0.46, 0.143, 0.04]);  

ImgResult_2 = axes ( ...
    "parent",   p2,...
    "position", [.19, 0.5, 0.15, 0.15]);
imgR_2 = imread("0.png");
axes(ImgResult_2);
imshow(imgR_2,[]);

imgR_3_label = uicontrol (...
  "parent", p2,...
  "style", "text",...
  "units","normalized",...
  "string", "",...
  "horizontalalignment", "center",...
  "foregroundcolor",[1 1 1],...
  "backgroundcolor",[0.85 0.85 0.85],...
  "position", [.363, 0.46, 0.143, 0.04]);  

ImgResult_3 = axes ( ...
    "parent",   p2,...
    "position", [.36, 0.5, 0.15, 0.15]); % + 0.17
imgR_3 = imread("0.png");
axes(ImgResult_3);
imshow(imgR_3,[]);

imgR_4_label = uicontrol (...
  "parent", p2,...
  "style", "text",...
  "units","normalized",...
  "string", "",...
  "horizontalalignment", "center",...
  "foregroundcolor",[1 1 1],...
  "backgroundcolor",[0.85 0.85 0.85],...
  "position", [.533, 0.46, 0.143, 0.04]);  

ImgResult_4 = axes ( ...
    "parent",   p2,...
    "position", [.53, 0.5, 0.15, 0.15]); % + 0.17
imgR_4 = imread("0.png");
axes(ImgResult_4);
imshow(imgR_4,[]);

imgR_5_label = uicontrol (...
  "parent", p2,...
  "style", "text",...
  "units","normalized",...
  "string", "",...
  "horizontalalignment", "center",...
  "foregroundcolor",[1 1 1],...
  "backgroundcolor",[0.85 0.85 0.85],...
  "position", [.703, 0.46, 0.143, 0.04]); 

ImgResult_5 = axes ( ...
    "parent",   p2,...
    "position", [.7, 0.5, 0.15, 0.15]); % + 0.17
imgR_5 = imread("0.png");
axes(ImgResult_5);
imshow(imgR_5,[]);

imgR_6_label = uicontrol (...
  "parent", p2,...
  "style", "text",...
  "units","normalized",...
  "string", "",...
  "horizontalalignment", "center",...
  "foregroundcolor",[1 1 1],...
  "backgroundcolor",[0.85 0.85 0.85],...
  "position", [.025, 0.26, 0.143, 0.04]);  % - 0.20

ImgResult_6 = axes ( ...
    "parent",   p2,...
    "position", [.02, 0.3, 0.15, 0.15]); % + 0.17
imgR_6 = imread("0.png");
axes(ImgResult_6);
imshow(imgR_6,[]);

imgR_7_label = uicontrol (...
  "parent", p2,...
  "style", "text",...
  "units","normalized",...
  "string", "",...
  "horizontalalignment", "center",...
  "foregroundcolor",[1 1 1],...
  "backgroundcolor",[0.85 0.85 0.85],...
  "position", [.193, 0.26, 0.143, 0.04]);  

ImgResult_7 = axes ( ...
    "parent",   p2,...
    "position", [.19, 0.3, 0.15, 0.15]); % + 0.17
imgR_7 = imread("0.png");
axes(ImgResult_7);
imshow(imgR_7,[]);

imgR_8_label = uicontrol (...
  "parent", p2,...
  "style", "text",...
  "units","normalized",...
  "string", "",...
  "horizontalalignment", "center", ...
  "foregroundcolor",[1 1 1],...
  "backgroundcolor",[0.85 0.85 0.85],...
  "position", [.363, 0.26, 0.143, 0.04]);  

ImgResult_8 = axes ( ...
    "parent",   p2,...
    "position", [.36, 0.3, 0.15, 0.15]); % + 0.17
imgR_8 = imread("0.png");
axes(ImgResult_8);
imshow(imgR_8,[]);

imgR_9_label = uicontrol (...
  "parent", p2,...
  "style", "text",...
  "units","normalized",...
  "string", "",...
  "horizontalalignment", "center",...
  "foregroundcolor",[1 1 1],...
  "backgroundcolor",[0.85 0.85 0.85],...
  "position", [.533, 0.26, 0.143, 0.04]);  

ImgResult_9 = axes ( ...
    "parent",   p2,...
    "position", [.53, 0.3, 0.15, 0.15]); % + 0.17
imgR_9 = imread("0.png");
axes(ImgResult_9);
imshow(imgR_9,[]);

imgR_10_label = uicontrol (...
  "parent", p2,...
  "style", "text",...
  "units","normalized",...
  "string", "",  ...
  "horizontalalignment", "center", ...
  "foregroundcolor",[1 1 1],...
  "backgroundcolor",[0.85 0.85 0.85],...
  "position", [.703, 0.256, 0.143, 0.04]); 

ImgResult_10 = axes ( ...
    "parent",   p2,...
    "position", [.7, 0.3, 0.15, 0.15]); % + 0.17
imgR_10 = imread("0.png");
axes(ImgResult_10);
imshow(imgR_10,[]);

%tic
%  fw = waitbar(0,'Please wait...');
%  for i = 1:10:100
%      waitbar(i/100,fw,'Project Initializing...');
%      pause(.5);
%  end
%  close(fw)
%toc 

imgR_11_label = uicontrol (...
  "parent", p2,...
  "style", "text",...
  "units","normalized",...
  "string", "",...
  "horizontalalignment", "center",...
  "foregroundcolor",[1 1 1],...
  "backgroundcolor",[0.85 0.85 0.85],...
  "position", [.025, 0.06, 0.143, 0.04]);  % - 0.20

ImgResult_11 = axes ( ...
    "parent",   p2,...
    "position", [.02, 0.1, 0.15, 0.15]); % + 0.17 - 2.0
imgR_11 = imread("0.png");
axes(ImgResult_11);
imshow(imgR_11,[]);

imgR_12_label = uicontrol (...
  "parent", p2,...
  "style", "text",...
  "units","normalized",...
  "string", "",...
  "horizontalalignment", "center",...
  "foregroundcolor",[1 1 1],...
  "backgroundcolor",[0.85 0.85 0.85],...
  "position", [.193, 0.06, 0.143, 0.04]);  

ImgResult_12 = axes ( ...
    "parent",   p2,...
    "position", [.19, 0.1, 0.15, 0.15]); % + 0.17
imgR_12 = imread("0.png");
axes(ImgResult_12);
imshow(imgR_12,[]);

imgR_13_label = uicontrol (...
  "parent", p2,...
  "style", "text",...
  "units","normalized",...
  "string", "",...
  "horizontalalignment", "center",...
  "foregroundcolor",[1 1 1],...
  "backgroundcolor",[0.85 0.85 0.85],...
  "position", [.363, 0.06, 0.143, 0.04]);  

ImgResult_13 = axes ( ...
    "parent",   p2,...
    "position", [.36, 0.1, 0.15, 0.15]); % + 0.17
imgR_13 = imread("0.png");
axes(ImgResult_13);
imshow(imgR_13,[]);

imgR_14_label = uicontrol (...
  "parent", p2,...
  "style", "text",...
  "units","normalized",...
  "string", "",...
  "horizontalalignment", "center",...
  "foregroundcolor",[1 1 1],...
  "backgroundcolor",[0.85 0.85 0.85],...
  "position", [.533, 0.06, 0.143, 0.04]);  

ImgResult_14 = axes ( ...
    "parent",   p2,...
    "position", [.53, 0.1, 0.15, 0.15]); % + 0.17
imgR_14 = imread("0.png");
axes(ImgResult_14);
imshow(imgR_14,[]);

imgR_15_label = uicontrol (...
  "parent", p2,...
  "style", "text",...
  "units","normalized",...
  "string", "",...
  "horizontalalignment", "center",...
  "foregroundcolor",[1 1 1],...
  "backgroundcolor",[0.85 0.85 0.85],...
  "position", [.703, 0.06, 0.143, 0.04]); 

ImgResult_15 = axes ( ...
    "parent",   p2,...
    "position", [.7, 0.1, 0.15, 0.15]); % + 0.17
imgR_15 = imread("0.png");
axes(ImgResult_15);
imshow(imgR_15,[]);


b2 = uicontrol (...
  "parent", p1,...
  "string", "Load Image Query",...
  "callback", {@load_image_query,ImgQuery,query_path,...
                ImgResult_1,ImgResult_2,ImgResult_3,ImgResult_4,ImgResult_5,...
                ImgResult_6,ImgResult_7,ImgResult_8,ImgResult_9,ImgResult_10,...
                ImgResult_11,ImgResult_12,ImgResult_13,ImgResult_14,ImgResult_15,...                    
                imgR_1_label, imgR_2_label, imgR_3_label, imgR_4_label, imgR_5_label,...
                imgR_6_label, imgR_7_label, imgR_8_label, imgR_9_label, imgR_10_label,...
                imgR_11_label, imgR_12_label, imgR_13_label, imgR_14_label, imgR_15_label,...
                precision,recall,fmeasure},...
  "position",[18 290 200 36]);

b3 = uicontrol (...
  "parent", p1,...
  "string", "Search",...
  "callback", {@search,database_path,query_path,method_choice,...
                    ImgResult_1,ImgResult_2,ImgResult_3,ImgResult_4,ImgResult_5,...
                    ImgResult_6,ImgResult_7,ImgResult_8,ImgResult_9,ImgResult_10,...
                    ImgResult_11,ImgResult_12,ImgResult_13,ImgResult_14,ImgResult_15,...                    
                    imgR_1_label, imgR_2_label, imgR_3_label, imgR_4_label, imgR_5_label,...
                    imgR_6_label, imgR_7_label, imgR_8_label, imgR_9_label, imgR_10_label,...
                    imgR_11_label, imgR_12_label, imgR_13_label, imgR_14_label, imgR_15_label,...
                    precision,recall,fmeasure},...
  "position",[18 150 200 36]);    

axis image off
%toc

 


